export const characters: any[] = [
    {
        id: 0,
        name: "Anakin Skywalker",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/anakin.png",
        arms: "",
        skill: "" 
    },  
    {
        id: 1,
        name: "Luke Skywalker",
        resume: "Até então um jovem órfão criado por um casal de fazendeiros de Tatooine, Luke descobre o seu destino ao cruzar com os droids C3PO e R2D2. Filho de Anakin Skywalker, encontra seu antigo mestre, Obi-Wan, salva a princesa Leia (que posteriormente descobriria ser sua irmã), destrói a principal arma do Império, a Estrela da Morte, se torna um dos líderes da Aliança Rebelde e finalmente ajuda a derrubar o Imperador Palpatine. No Episódio VII será mostrado já como um experiente mestre Jedi.",
        planet: "Tatooine",
        specie: "Humano",
        memorablePhrase: "'Eu nunca vou cair para o lado escuro. Você falhou, alteza. Sou um Jedi, como meu pai antes de mim'",
        icon: "",
        image: "../../images/luke.png",
        arms: "Sabre de luz verde",
        skill: "Jedi"
    },
    {
        id: 2,
        name: "Princesa Leia",
        resume: "Leia Organa (nascida Leia Amidala Skywalker) é uma das protagonistas da trilogia clássica (Episódios IV, V e VI). É irmã gêmea de Luke Skywalker e filha biológica da ex-rainha de Naboo Padmé Amidala e do Cavaleiro Jedi Anakin Skywalker. Leia nasceu no final da Guerras Clônicas. Com a morte de sua mãe e a transformação de seu pai em Darth Vader, foi separada de seu irmão gêmeo e entregue aos cuidados do Senador Bail Organa e de sua esposa Breha Organa. Bail encabeçava a família real de Alderaan, o que conferiu a Leia o título de princesa. Foi uma das líderes da Aliança Rebelde e também é uma sensitiva da força, assim como seu pai e seu irmão Luke. A princesa também mantém um romance cheio de altos e baixos com Han Solo. Em O Despertar da Força, Leia não é mais chamada de princesa, mas sim de General. É a líder da Resistência na luta contra a Nova Ordem, comandada pelo General Hux.",
        planet: "Alderaan",
        specie: "Humano",
        memorablePhrase: "Ajude-me, ObiWan, você é minha ultima esperança",
        icon: "",
        image: "../../images/leia.png",
        arms: "Blaster",
        skill: "Política" 
    },
    {
        id: 3,
        name: "Han Solo",
        resume: "Um dos personagens mais queridos da história do cinema: o ex-piloto e contrabandista Han Solo terá presença marcada no filme Star Wars: O Despertar da Força. Ele e seu copiloto Chewbacca passaram a acreditar na causa da liberdade galáctica, juntando­se a Luke Skywalker e à princesa Leia Organa na luta contra o Império. Contrabandista, ordinário e herói, Han Solo é um dos grandes líderes da Aliança Rebelde e da Nova República posteriormente, além de ser Capitão da Millennium Falcon, a nave mais veloz da galáxia.",
        planet: "Corellia",
        specie: "Humano",
        memorablePhrase: "Já voei de um lado a outro nesta galáxia... e já vi muita coisa estranha... mas nunca vi nada que me fizesse acreditar... que existe uma força poderosa controlando tudo. Nenhum campo de energia mística controla meu destino. É tudo bobagem e um monte de truques baratos .",
        icon: "",
        image: "../../images/hansolo.png",
        arms: "Pistola Mauser",
        skill: "Tiro" 
    },
    {
        id: 4,
        name: "Darth Vader",
        resume: "Uma das figuras centrais da saga, Anakin é um dos mais lendários entre os cavaleiros Jedi. Ele serviu a República Galáctica, mas acabou tornando-se o lorde negro Sith conhecido como Darth Vader. Teve uma vida sofrida como escravo em Tatooine, mas foi libertado pelo Jedi Qui-Gon Jinn, que o fez ingressar na ordem Jedi. Mais tarde, passou para o Lado Negro da Força como aprendiz de Darth Sidious.",
        planet: "Tatooine",
        specie: "Humano",
        memorablePhrase: "Luke, eu sou seu pai!",
        icon: "",
        image: "../../images/darthvader.png",
        arms: "Sabre de luz azul / vermelho",
        skill: "Exímio estrategista e piloto, também possuia muita habilidade na fabricação de aparatos mecânicos. Como Darth Vader tinha grande habilidade com o sabre de luz." 
    },
    {
        id: 5,
        name: "R2-D2",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/R2D2.png",
        arms: "",
        skill: "" 
    },
    {
        id: 6,
        name: "C-3PO",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/C3PO.png",
        arms: "",
        skill: "" 
    },
    {
        id: 7,
        name: "Chewbacca",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/chewbacca.png",
        arms: "",
        skill: "" 
    },
    {
        id: 8,
        name: "Obi-Wan Kenobi",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/obiwan.png",
        arms: "",
        skill: "" 
    },
    {
        id: 9,
        name: "Yoda",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/yoda.png",
        arms: "",
        skill: "" 
    },
    {
        id: 10,
        name: "Padmé Amidala",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/amidala.png",
        arms: "",
        skill: "" 
    },
    {
        id: 11,
        name: "Stormtrooper",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/stormtrooper.png",
        arms: "",
        skill: "" 
    },
    {
        id: 12,
        name: "Darth Sidious",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/sidious.png",
        arms: "",
        skill: "" 
    },
    {
        id: 13,
        name: "Lando",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/lando.png",
        arms: "",
        skill: "" 
    },
    {
        id: 14,
        name: "Rey",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/rey.png",
        arms: "",
        skill: "" 
    },
    {
        id: 15,
        name: "Poe Dameron",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/dameron.png",
        arms: "",
        skill: "" 
    },
    {
        id: 16,
        name: "Kylo Ren",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/kyloren.png",
        arms: "",
        skill: "" 
    },
    {
        id: 17,
        name: "General Hux",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/generalhux.png",
        arms: "",
        skill: "" 
    },
    {
        id: 18,
        name: "Capitã Phasma",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/pashma.png",
        arms: "",
        skill: "" 
    },
    {
        id: 19,
        name: "Qui-Gon Jinn",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/quin.png",
        arms: "",
        skill: "" 
    },
    {
        id: 20,
        name: "Mace Windu",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/mace.png",
        arms: "",
        skill: "" 
    },
    {
        id: 21,
        name: "Jabba O Hutt",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/jabba.png",
        arms: "",
        skill: "" 
    },
    {
        id: 22,
        name: "Boba Fett",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/boba.png",
        arms: "",
        skill: "" 
    },
    {
        id: 23,
        name: "Conde Dooku",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/dooku.png",
        arms: "",
        skill: "" 
    },
    {
        id: 24,
        name: "Governador Tarkin",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/generaltarkin.png",
        arms: "",
        skill: "" 
    },
    {
        id: 25,
        name: "Almirante Ackbar",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/ackbar.png",
        arms: "",
        skill: "" 
    },
    {
        id: 26,
        name: "General Grievous",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/grievous.png",
        arms: "",
        skill: "" 
    },
    {
        id: 27,
        name: "Jango Fett",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/jango.png",
        arms: "",
        skill: "" 
    },
    {
        id: 28,
        name: "Darth Maul",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/darthmaul.png",
        arms: "",
        skill: "" 
    },
    {
        id: 29,
        name: "Jar Jar Binks",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/jarjar.png",
        arms: "",
        skill: "" 
    },
    {
        id: 30,
        name: "Palpatine",
        resume: "",
        planet: "",
        specie: "",
        memorablePhrase: "",
        icon: "",
        image: "../../images/palpatine.png",
        arms: "",
        skill: "" 
    }      
]