export const characters: any[] = [
    {
        id: 0,
        name: "Anakin Skywalker",
        resume: "Uma das figuras centrais da saga, Anakin é um dos mais lendários entre os cavaleiros Jedi. Ele serviu a República Galáctica, mas acabou tornando-se o lorde negro Sith conhecido como Darth Vader. Teve uma vida sofrida como escravo em Tatooine, mas foi libertado pelo Jedi Qui-Gon Jinn, que o fez ingressar na ordem Jedi. Mais tarde, passou para o Lado Negro da Força como aprendiz de Darth Sidious.",
        planet: "Tatooine",
        specie: "Humano",
        memorablePhrase: "Agora a diversão vai começar.",
        icon: "",
        image: "../../images/anakin.png",
        arms: "Sabre de luz azul",
        skill: "Exímio estrategista e piloto, também possuía muita habilidade na fabricação de aparatos mecânicos. Como Darth Vader tinha grande habilidade com o sabre de luz." 
    },  
    {
        id: 1,
        name: "Luke Skywalker",
        resume: "Até então um jovem órfão criado por um casal de fazendeiros de Tatooine, Luke descobre o seu destino ao cruzar com os droids C3PO e R2D2. Filho de Anakin Skywalker, encontra seu antigo mestre, Obi-Wan, salva a princesa Leia (que posteriormente descobriria ser sua irmã), destrói a principal arma do Império, a Estrela da Morte, se torna um dos líderes da Aliança Rebelde e finalmente ajuda a derrubar o Imperador Palpatine. No Episódio VII será mostrado já como um experiente mestre Jedi.",
        planet: "Tatooine",
        specie: "Humano",
        memorablePhrase: "Eu nunca vou cair para o lado escuro. Você falhou, alteza. Sou um Jedi, como meu pai antes de mim",
        icon: "",
        image: "../../images/luke.png",
        arms: "Sabre de luz verde",
        skill: "Jedi"
    },
    {
        id: 2,
        name: "Princesa Leia",
        resume: "Leia Organa (nascida Leia Amidala Skywalker) é uma das protagonistas da trilogia clássica (Episódios IV, V e VI). É irmã gêmea de Luke Skywalker e filha biológica da ex-rainha de Naboo Padmé Amidala e do Cavaleiro Jedi Anakin Skywalker. Leia nasceu no final da Guerras Clônicas. Com a morte de sua mãe e a transformação de seu pai em Darth Vader, foi separada de seu irmão gêmeo e entregue aos cuidados do Senador Bail Organa e de sua esposa Breha Organa. Bail encabeçava a família real de Alderaan, o que conferiu a Leia o título de princesa. Foi uma das líderes da Aliança Rebelde e também é uma sensitiva da força, assim como seu pai e seu irmão Luke. A princesa também mantém um romance cheio de altos e baixos com Han Solo. Em O Despertar da Força, Leia não é mais chamada de princesa, mas sim de General. É a líder da Resistência na luta contra a Nova Ordem, comandada pelo General Hux.",
        planet: "Alderaan",
        specie: "Humano",
        memorablePhrase: "Ajude-me, ObiWan, você é minha ultima esperança",
        icon: "",
        image: "../../images/leia.png",
        arms: "Blaster",
        skill: "Política" 
    },
    {
        id: 3,
        name: "Han Solo",
        resume: "Um dos personagens mais queridos da história do cinema: o ex-piloto e contrabandista Han Solo terá presença marcada no filme Star Wars: O Despertar da Força. Ele e seu copiloto Chewbacca passaram a acreditar na causa da liberdade galáctica, juntando­se a Luke Skywalker e à princesa Leia Organa na luta contra o Império. Contrabandista, ordinário e herói, Han Solo é um dos grandes líderes da Aliança Rebelde e da Nova República posteriormente, além de ser Capitão da Millennium Falcon, a nave mais veloz da galáxia.",
        planet: "Corellia",
        specie: "Humano",
        memorablePhrase: "Já voei de um lado a outro nesta galáxia... e já vi muita coisa estranha... mas nunca vi nada que me fizesse acreditar... que existe uma força poderosa controlando tudo. Nenhum campo de energia mística controla meu destino. É tudo bobagem e um monte de truques baratos .",
        icon: "",
        image: "../../images/hansolo.png",
        arms: "Pistola Mauser",
        skill: "Tiro" 
    },
    {
        id: 4,
        name: "Darth Vader",
        resume: "Uma das figuras centrais da saga, Anakin é um dos mais lendários entre os cavaleiros Jedi. Ele serviu a República Galáctica, mas acabou tornando-se o lorde negro Sith conhecido como Darth Vader. Teve uma vida sofrida como escravo em Tatooine, mas foi libertado pelo Jedi Qui-Gon Jinn, que o fez ingressar na ordem Jedi. Mais tarde, passou para o Lado Negro da Força como aprendiz de Darth Sidious.",
        planet: "Tatooine",
        specie: "Humano",
        memorablePhrase: "Luke, eu sou seu pai!",
        icon: "",
        image: "../../images/darthvader.png",
        arms: "Sabre de luz azul / vermelho",
        skill: "Exímio estrategista e piloto, também possuia muita habilidade na fabricação de aparatos mecânicos. Como Darth Vader tinha grande habilidade com o sabre de luz." 
    },
    {
        id: 5,
        name: "R2-D2",
        resume: "R2-D2 foi um droide astromecânico série R2 corajoso e de personalidade forte que sempre nutriu gosto por aventuras. Ele é versátil e possui diversas habilidades, de extintor de incêndio a comunicador por hologramas.",
        planet: "Naboo",
        specie: "Droide astromecânico",
        memorablePhrase: "Beep, beep, beep.",
        icon: "",
        image: "../../images/R2D2.png",
        arms: "Serra e bastão.",
        skill: "Possui inúmeras ferramentas como serra elétrica, solda, projetor holográfico e propulsor de foguete." 
    },
    {
        id: 6,
        name: "C-3PO",
        resume: "C-3PO foi um droide de protocolo com a capacidade de falar e entender praticamente todos os idiomas conhecidos. Sempre muito leal aos donos ele ajudou os rebeldes e serviu à Princesa Leia na importante missão de levar informações secretas sobre a Estrela da Morte ao mestre Obi-Wan Kenobi.",
        planet: "Affa (reconstruído em Tatooine)",
        specie: "Droide de protocolo",
        memorablePhrase: "Eu sou C-3PO, ciborgue de relações humanas e fluente em 6 milhões de línguas e falas de comunicações diferentes.",
        icon: "",
        image: "../../images/C3PO.png",
        arms: "Não possui armas.",
        skill: "Fluente em mais de 6 milhões de línguas." 
    },
    {
        id: 7,
        name: "Chewbacca",
        resume: "“Chewie” para os íntimos, o peludo co-piloto da Millennium Falcon é um Wookie, natural do planeta Kashyyyk. Inteligente e leal, é também um excelente mecânico, capaz de consertar a nave de Han Solo e até mesmo o dróide C-3PO. Depois que Han salvou sua vida, passou a segui-lo para pagar sua dívida de honra, tornando-se melhores amigos. Foi Chewie quem influenciou o contrabandista a ajudar os rebeldes contra o Império. Comunica-se em Shyriiwook, uma língua composta de rosnados e grunhidos, e usa como arma uma besta a laser. Um dos personagens mais queridos da trilogia original, o Wookie tem uma breve participação no Episódio III e voltará em Star Wars: O despertar da Força.",
        planet: "Kashyyyk",
        specie: "Wookie",
        memorablePhrase: "",
        icon: "“Grrrrowr”, “Rowwwwr”, “Awrrr-awr-awr!”",
        image: "../../images/chewbacca.png",
        arms: "Besta a laser.",
        skill: "Mecânica; arrancar os braços de quem ganha dele no xadrez." 
    },
    {
        id: 8,
        name: "Obi-Wan Kenobi",
        resume: "Um dos mais respeitados mestres Jedi da Antiga República, Obi-Wan Kenobi foi mentor tanto de Anakin Skywaler (que posteriormente viria a se tornar Darth Vader) quanto do seu filho, Luke. Especialista em infiltração, foi um dos principais comandantes nas Guerras Clônicas e, ao fim do conflito, com a extinção dos Jedi, tomou para si a responsabilidade de guardar o filho do seu antigo amigo.",
        planet: "Stewjon",
        specie: "Humano",
        memorablePhrase: "Se você me derrubar, me tornarei mais poderoso do que você pode imaginar.",
        icon: "",
        image: "../../images/obiwan.png",
        arms: "Sabre de luz azul",
        skill: "Mestre Jedi" 
    },
    {
        id: 9,
        name: "Yoda",
        resume: "Um dos mais antigos membros do Conselho Jedi, Mestre Yoda treina novos padawans há pelo menos 800 anos. Tido como um dos Jedi mais poderoso de todos os tempos, falhou em perceber a aproximação dos Sith que causou o fim da República, mas treinou Luke Skywalker para que pudesse derrotar o Império.",
        planet: "Desconhecido",
        specie: "Desconhecida",
        memorablePhrase: "Julga-me pelo meu tamanho? Hun? E não deveria. Aliada minha a Força é. E poderosa aliada ela é.",
        icon: "",
        image: "../../images/yoda.png",
        arms: "Sabre de luz verde",
        skill: "Mestre Jedi" 
    },
    {
        id: 10,
        name: "Padmé Amidala",
        resume: "Eleita aos 14 anos Rainha de Naboo, posteriormente representou seu planeta no Senado Galáctico. É uma das principais personagens da trilogia mais recente. Por segurança, frequentemente se disfarçava como uma de suas damas de companhia enquanto uma sósia assumia seu lugar; deste modo escapou de ao menos um atentado contra sua vida. Conheceu Anakin Skywalker quando este ainda era uma criança e, anos mais tarde, casou-se em segredo com o jovem Jedi. De coração partido ao se dar conta de que Anakin havia se rendido ao Lado Negro da Força, Padmé deu à luz um casal de gêmeos, Luke Skywalker e Leia Organa, e morreu pouco após o parto.",
        planet: "Naboo",
        specie: "Humana",
        memorablePhrase: "Então é assim que morre a liberdade: com um estrondoso aplauso!",
        icon: "",
        image: "../../images/amidala.png",
        arms: "Pistola Blaster Real.",
        skill: "Política" 
    },
    {
        id: 11,
        name: "Stormtrooper",
        resume: "Principal unidade do exército da Antiga República e do Imperio. Inicialmente, era formado por clones do caçador de recompensas Jango Fett, produzidos em Kamino e geneticamente engenhados para serem os soldados perfeitos. Posteriormente, com o avanço das Guerras Clônicas e a destruição de Kamino, são substituidos por humanos normais (só humanos, nunca alienígenas).",
        planet: "Kamino",
        specie: "Humanos",
        memorablePhrase: "Esses não são os droids que estamos procurando... Não preciso ver a sua identificação. Continue, continue...",
        icon: "",
        image: "../../images/stormtrooper.png",
        arms: "Rifle laser E-11.",
        skill: "Na trilogia nova, soldados perfeitos. Na antiga, não acertam nenhum tiro e são derrotados por Ewoks." 
    },
    {
        id: 12,
        name: "Darth Sidious",
        resume: "Principal vilão de Star Wars, o Imperador Palpatine é um dos Lordes Sith mais poderosos da história, que atende pelo nome de Darth Sidious. Graças as suas habilidades de manipulação, foi o responsável pela destruição da Ordem Jedi e pela instauração do Império Galáctico. Como senador de Naboo, ele articulou secretamente uma série de eventos que o tornaram chanceler da Velha República e, durante as Guerras Clónicas, acumulou poderes emergenciais até se auto-proclamar imperador. Foi o responsável por trazer o jovem aprendiz Anakim Skywalker para o lado negro da força, quando assumiu o título de Darth Vader. Morreu pouco antes da explosão da segunda Estrela da Morte, durante a batalha de Endor",
        planet: "Naboo",
        specie: "Humano",
        memorablePhrase: "O filho de Skywalker não deve se tornar um Jedi.",
        icon: "",
        image: "../../images/sidious.png",
        arms: "Raios da Força e Sabre de luz",
        skill: "Manipulação" 
    },
    {
        id: 13,
        name: "Lando",
        resume: "Ex-contrabandista, Lando é um dos melhores amigos de Han Solo. Ele foi o primeiro dono da famosa nave Millenium Falcon, mas a perdeu para o amigo em uma aposta. Mais tarde, ameaçado por Darth Vader, Lando traiu Han Solo fazendo com que ele fosse congelado em carbonita e entregue ao caçador de recompensas Boba Fett. Arrependido, ele ajudou Leia e Luke a libertar Han das garras de Jabba the Hutt. Durante a batalha de Endor, foi Lando, como piloto da Millenium Falcon, que liderou o ataque dos caças e destruiu a segunda Estrela da Morte.",
        planet: "Socorro",
        specie: "Humano",
        memorablePhrase: "Eu sou responsável agora. É o preço que se paga por ser bem sucedido.",
        icon: "",
        image: "../../images/lando.png",
        arms: "Blaster",
        skill: "Piloto" 
    },
    {
        id: 14,
        name: "Rey",
        resume: "Uma das protagonistas da nova trilogia, Rey é uma escavadora no planeta desértico de Jakku, de filiação desconhecida, que se une a Fynn, Han Solo e Chewbacca em uma missão após ser perseguida pela Primeira Ordem. Assim como outros personagens da franquia, é boa piloto e vive acompanhada o BB-8.",
        planet: "Jakku",
        specie: "Humano",
        memorablePhrase: "Eu sou ninguém.",
        icon: "",
        image: "../../images/rey.png",
        arms: "Bastão e blaster",
        skill: "Escavadora" 
    },
    {
        id: 15,
        name: "Poe Dameron",
        resume: "Poe Dameron é o principal piloto da Resistência e mestre do droide BB-8. Foi o responsável por liderar o ataque à base Starkiller e guardar o mapa com a localização de Luke Skywalker.",
        planet: "Yavin 4",
        specie: "Humano",
        memorablePhrase: "Eu sou um oficial da república, General. Fiz um juramento para proteger a República",
        icon: "",
        image: "../../images/dameron.png",
        arms: "Desconhecido",
        skill: "Piloto" 
    },
    {
        id: 16,
        name: "Kylo Ren",
        resume: "Antes do lançamento do Episódio VII - O despertar da Força, muito pouco se sabe sobre Kylo Ren. Ele é membro de uma ordem chamada Cavaleiros de Ren e um dos comandantes da Primeira Ordem, que sucedeu o Império. Guarda uma devoção pela figura de Darth Vader e está em busca de objetos relacionados ao lorde Sith.",
        planet: "Chandrila",
        specie: "Humano",
        memorablePhrase: "Nada ficará em nosso caminho. Terminarei o que você começou",
        icon: "",
        image: "../../images/kyloren.png",
        arms: "Sabre de luz customizado",
        skill: "Aparentemente, as mesmas de um Lorde Sith" 
    },
    {
        id: 17,
        name: "General Hux",
        resume: "General Hux é o comandante do Exército da Nova Ordem e chefe da Base/Estação bélica Starkiller. É o braço direito do Líder Supremo Snoke e nutre verdadeiro ódio da Nova República e da Resistência.",
        planet: "Arkanis",
        specie: "Humano",
        memorablePhrase: "",
        icon: "",
        image: "../../images/generalhux.png",
        arms: "Desconhecido",
        skill: "Desconhecido" 
    },
    {
        id: 18,
        name: "Capitã Phasma",
        resume: "Capitã da Primeira Ordem, não há muitos detalhes sobre ela. Sua armadura de assemelha a de um stormtrooper, mas é cromada e possui uma longa capa negra.",
        planet: "Desconhecido",
        specie: "Humano",
        memorablePhrase: "Mova suas naves agora.",
        icon: "",
        image: "../../images/pashma.png",
        arms: "Espingarda blaster com mira de precisão",
        skill: "Desconhecido" 
    },
    {
        id: 19,
        name: "Qui-Gon Jinn",
        resume: "Um dos mais poderosos jedis, Qui­Gon Jinn foi mestre de Obi­Wan Kenobi, descobridor de Anakin Skywalker e auxiliou no resgate da rainha Amidala. Um homem considerado um dissidente pelos seus iguais, mas muito amado por aqueles que o conheciam. Interpretado nas telonas pelo ator Liam Neeson, Qui­Gon Jinn foi treinado por Conde Dookan, de onde herdou a maior parte de sua forte personalidade, e foi morto em Naboo pelo Darth Maul. Jinn continuou a ter uma grande influência no futuro dos Jedi, mesmo depois de morto.",
        planet: "Desconhecido",
        specie: "Humano",
        memorablePhrase: "O nosso encontro não foi coincidência. Nada acontece por acaso",
        icon: "",
        image: "../../images/quin.png",
        arms: "Sabre de luz verde",
        skill: "O segredo da imortalidade" 
    },
    {
        id: 20,
        name: "Mace Windu",
        resume: "Natural do planeta Haruun Kal, o Mestre Jedi ocupava o segundo lugar no Alto Conselho, abaixo apenas do Grande Mestre Yoda. Apareceu pela primeira vez em Star Wars: A ameaça fantasma. Inicialmente foi contra o treinamento de Anakin Skywalker, mas acabou consentindo que este se tornasse aprendiz de Obi-Wan Kenobi. Considerado um dos maiores guerreiros de sua Ordem, teve importante participação comandando os Cavaleiros Jedi nas Guerras Clônicas do Episódio II. No Episódio III, após ser informado por Anakin que o Chanceler Palpatine seria o Mestre Sith Darth Sidious, Windu tenta prender o Chanceler. Skywalker intervém na luta e desarma Mace, que acaba morto pelo Sith.",
        planet: "Haruun Kal",
        specie: "Humano",
        memorablePhrase: "Em nome do Senado Galáctico da República, o senhor está preso, Chanceler.",
        icon: "",
        image: "../../images/mace.png",
        arms: "Sabre de luz roxo",
        skill: "Considerado o mais poderoso Jedi em combate." 
    },
    {
        id: 21,
        name: "Jabba O Hutt",
        resume: "Jabba o Hutt foi um dos mais poderosos gângsteres da galáxia, com influência tanto em política quanto no submundo do crime. Mencionado no primeiro filme da série, Uma Nova Esperança, como o credor de Han Solo, Jabba fez sua primeira aparição física em O Retorno de Jedi, no qual Luke lidera uma equipe que tenta resgatar Solo. No final, o alienígena com aspecto de lesma foi morto por Leia, que com uma corrente o sufocou até a morte.",
        planet: "Nal Hutta",
        specie: "Hutt",
        memorablePhrase: "Han, meu garoto, você me decepcionou. Por que não me pagou? E por que matou o pobre Greedo?",
        icon: "",
        image: "../../images/jabba.png",
        arms: "Desconhecido",
        skill: "Engolir coisas" 
    },
    {
        id: 22,
        name: "Boba Fett",
        resume: "Boba Fett foi um clone inalterado de Jango Fett. Criado como seu filho, viu seu pai ser morto por um Jedi ainda criança. Sozinho, Boba procurou a ajuda de Jabba o Hutt, que o ajudou em troca de uma dívida que ele possuía com Jango. Mesmo órfão ainda jovem, Boba sobreviveu às Guerras Clônicas e à Guerra Civil Galática e tornou-se o mais temido e sinistro caçador de recompensas da Galáxia. Sua fama era tamanha que prestou alguns serviços diretamente a Darth Vader, segundo no comando do Império. Foi o responsável por capturar seu rival Han Solo com a ajuda do Império e entregá-lo a Jabba. Morreu durante o resgate de Solo ao cair acidentalmente no Poço de Carkoon, lar do perigoso Sarlacc, sendo devorado pelo mesmo.",
        planet: "Kamino",
        specie: "Humano",
        memorablePhrase: "Todos morrem. É a única justiça que restou",
        icon: "",
        image: "../../images/boba.png",
        arms: "Rifle EE-3 e Jetpack",
        skill: "Caçador de Recompensas" 

    },
    {
        id: 23,
        name: "Conde Dooku",
        resume: "Conde Dooku (conhecido no Brasil como Conde Dookan a fim de evitar trocadilhos) foi o Mestre Jedi mentor de Qui­Gon Jinn, mas caiu para o lado negro da Força e se tornou o Lorde Negro dos Sith, conhecido como Darth Tyranus. Dooku é assassinado por Anakin Skywalker, que toma seu lugar como o novo aprendiz de Darth Sidious, Darth Vader. Dookan era um instrutor respeitado no Templo Jedi e um dos mais renomados espadachins da galáxia.",
        planet: "Serenno",
        specie: "Humano",
        memorablePhrase: "Bom. Duas vezes o orgulho, o dobro da queda!",
        icon: "",
        image: "../../images/dooku.png",
        arms: "Sabre de luz e raios da força",
        skill: "Poucos Mestres Jedi foram equiparados à habilidade de Dookan com um sabre de luz" 
    },
    {
        id: 24,
        name: "Governador Tarkin",
        resume: "Wilhuff Tarkin foi um dos indivíduos mais poderosos do Império Galáctico. Ele atuou como capitão durante as Guerras Clônicas. Quando o Supremo Chanceler Sheev Palpatine transformou a República no Império, Tarkin tornou­se governador regional da Orla Exterior. Ele foi o principal colaborador por trás da criação que seria sua encarnação chave, a Estrela da Morte.",
        planet: "Eriadu",
        specie: "Humano",
        memorablePhrase: "Evacuar? No nosso momento de triunfo? Eu acho que você superestimar suas chances!",
        icon: "",
        image: "../../images/generaltarkin.png",
        arms: "Estrela da Morte",
        skill: "Criação de super armas, como a Estrela da Morte." 
    },
    {
        id: 25,
        name: "Almirante Ackbar",
        resume: "Importante militar da Aliança Rebelde, Gial Ackbar, da raça Mon Calamari, nasceu no planeta aquático Dac. Em O retorno de Jedi, o comandante participou do ataque que levaria à destruição da Estrela da Morte II. Sua frase “É uma armadilha!” é uma das mais falas mais famosas do filme. O personagem deve retornar em Star Wars: O despertar da Força.",
        planet: "Dac",
        specie: "Mon Calamari",
        memorablePhrase: "É uma armadilha!",
        icon: "",
        image: "../../images/ackbar.png",
        arms: "Sua nave, o Cruzador Estelar Home One",
        skill: "Táticas militares" 
    },
    {
        id: 26,
        name: "General Grievous",
        resume: "General Grievous, cujo nome verdadeiro é Qymaen jai Sheelal, foi o líder das forças militares da Confederação de Sistemas Independentes e grande inimigo da República. Seu corpo é uma fusão de partes orgânicas com uma poderosa estrutura ciborgue. É conhecido como assassino de Jedis e coleciona artefatos de seus oponentes derrotados.",
        planet: "Kalee",
        specie: "Kaleesh",
        memorablePhrase: "Eu não sou um droide",
        icon: "",
        image: "../../images/grievous.png",
        arms: "Sabre de luz",
        skill: "Seu corpo robótico super forte o permite lutar com até seis sabres de luz ao mesmo tempo ao dividir seus braços em quatro e usar sabres até nos pés." 
    },
    {
        id: 27,
        name: "Jango Fett",
        resume: "Jango Fett foi um conhecido caçador de recompensas mandaloriano. Nascido em Concord Dawn, foi adotado por guerreiros mandalorianos após o assassinato de seus pais. Tornou-se caçador de recompensas após destruir os Death Watch, um grupo terrorista mandaloriano responsável pela morte de seu mentor. Após ganhar reputação como um dos melhores da galáxia, Jango aceitou ser o modelo genético para os clones que fariam parte do Exército da República. Ao ser confrontado pelo Mestre Jedi Obi-Wan Kenobi, Jango foge ao encontro do Líder Separatista, o Lorde Sith Conde Dooku. Jango foi morto pelo Mestre Jedi Mace Windu durante a Batalha de Geonosis. Além dos milhares de soldados clones, o legado de Jango continuou com Boba Fett, que embora fosse mais um clone seu, foi criado como filho.",
        planet: "Mandalore",
        specie: "Humano",
        memorablePhrase: "Eu sou apenas um homem simples tentando se virar nesse universo.",
        icon: "",
        image: "../../images/jango.png",
        arms: "Rifle EE-3",
        skill: "Caçador de Recompensas" 
    },
    {
        id: 28,
        name: "Darth Maul",
        resume: "Primeiro aprendiz de Darth Sidious, Darth Maul foi preparado para ser um assassino Sith habilmente treinado na esgrima, possuindo um sabre de luz duplo. Ao seguir a rainha Padmé Amidala em Tatooine, foi ele quem revelou para a Ordem Jedi a existência dos Sith. Mais tarde, durante a batalha de Naboo, Maul liderou o exército de droides da Federação de Comércio. Durante a luta, ele matou o mestre Jedi Qui-Gon Jinn, mas foi derrotado em seguida pelo seu aprendiz Obi-Wan Kenobi.",
        planet: "Dathomir",
        specie: "Zabrak",
        memorablePhrase: "Morra, Jedi. Morra!",
        icon: "",
        image: "../../images/darthmaul.png",
        arms: "Sabre de luz duplo",
        skill: "Assassino" 
    },
    {
        id: 29,
        name: "Jar Jar Binks",
        resume: "Jar Jar Binks é um membro da raça Gungan que fez parte da equipe de apoio da senadora Padmé Amidala. Ingênuo e leal ele acompanhou Qui-Gon Jinn na invasão de Naboo e viajou por mundos como Tatooine e Coruscant, algo raro para um gungan.",
        planet: "Naboo",
        specie: "Otola Gungan",
        memorablePhrase: "Este sol acaba com a minha pele",
        icon: "",
        image: "../../images/jarjar.png",
        arms: "Nenhuma",
        skill: "Como parte de uma raça anfíbia consegue respirar embaixo d'água e possui agilidade ao nadar." 
    },
    {
        id: 30,
        name: "Palpatine",
        resume: "Principal vilão de Star Wars, o Imperador Palpatine é um dos Lordes Sith mais poderosos da história, que atende pelo nome de Darth Sidious. Graças as suas habilidades de manipulação, foi o responsável pela destruição da Ordem Jedi e pela instauração do Império Galáctico. Como senador de Naboo, ele articulou secretamente uma série de eventos que o tornaram chanceler da Velha República e, durante as Guerras Clónicas, acumulou poderes emergenciais até se auto-proclamar imperador. Foi o responsável por trazer o jovem aprendiz Anakim Skywalker para o lado negro da força, quando assumiu o título de Darth Vader. Morreu pouco antes da explosão da segunda Estrela da Morte, durante a batalha de Endor.",
        planet: "Naboo",
        specie: "Humano",
        memorablePhrase: "O lado sombrio é o caminho para várias habilidades que alguns consideram como não-naturais.",
        icon: "",
        image: "../../images/palpatine.png",
        arms: "Raios da força e sabre de luz",
        skill: "Manipulação" 
    }      
]